version: '2'
services:
  ipalert:
    build: .
    image: mfournier/ipalert:latest
    container_name: ipalert
    volumes:
      - ./data:/app/data
      - ./ssmtp.conf:/etc/ssmtp/ssmtp.conf
    environment:
      - "host="
      - "recipient="

